### ISSUE TITLE
请求保存 Cookie

### ISSUE THREAD

**Issue by killerDK** [CakeAL/ustb-wifi-tools#1]
每次打开软件都需要重新登陆以获取 Cookie，请求保存 Cookie 。

**Comment by CakeAL** [comment]
正在开发保存账号和密码到本地，以实现自动登录的功能，那个 Cookie 的有效期比较短，下次打开不一定还能用了。

**Comment by CakeAL** [comment]
This issue has been resolved in [USTB WiFi Tools v0.5.1](https://github.com/CakeAL/ustb-wifi-tools/releases/tag/v0.5.1).
