### ISSUE TITLE
请求添加/修改功能

### ISSUE THREAD

**Issue by moaizhi666** [CakeAL/ustb-wifi-tools#3]
月度概览页面：
1.能否直接显示本月月度概览，保留选择月份功能；
2.能否添加Mb和G显示单位切换按钮（功能）;
原因：
1.我个人比较喜欢看每天花出去了多少流量，就好像看账本每天自己花出去多少钱一样；
2.每天用的流量比较多，用G为单位显示感觉更舒服。

**Comment by CakeAL** [comment]
感谢支持，已在 https://github.com/CakeAL/ustb-wifi-tools/releases/tag/v0.8.9 修改。

**Comment by moaizhi666** [comment]
谢谢
