### ISSUE TITLE
v6网络有关问题

### ISSUE THREAD

**Issue by LYOfficial** [CakeAL/ustb-wifi-tools#4]
在你科注销页显示的V6流量标题为 **登录前流量(V6):xxxMB** 

想知道这个v6流量是实时统计的还是只计算登录前消耗的v6流量？

还有一个问题，就是你科校园网v4和v6是一体的，如果在网络控制关闭IPV4只保留IPV6，校园网就会断线，原因大概是不能访问到注销页登录账号，有没有什么方法保持自己账号登录，在不跑v4流量的情况下放心使用IPV6？

**Comment by CakeAL** [comment]
1. **登录前流量(V6):xxxMB**（参考我的应用里面`月度使用概览`里面说的），因为校园网每次都需要等你下线之后，才能记录一次数据，之后把当月的累加，就是所谓的**登录前**，也就是说注销页的数据不是实时的，就是距你这次联上校园网之前，ipv4和ipv6的下行。
2. 登录校园网之后，关闭ipv4，校园网不会断开，只用ipv6是可以的，比如访问纯ipv6网站(https://mirrors6.tuna.tsinghua.edu.cn/)，但是你需要设置ipv6 DNS来提供ipv6的域名解析服务，因为默认情况下没有设置的话，需要先向ipv4的DNS服务器发查询ip的请求，但是此时ipv4关闭，所以无法获取域名对应的地址。但是有ipv6 DNS的话就可以直接对域名解析。或者使用直接ipv6访问例如(https://[2001:da8:208:10::14]/)。关于不跑v4流量情况下使用v6，这是不可能的，因为现在整个互联网底层还是ipv4

**Comment by CakeAL** [comment]
你可以试一下连接校园网，然后断开ipv4，上述两个网站仍可以访问。第一个需要配置ipv6 DNS，第二个不需要配置ipv6 DNS
